### ISSUE TITLE
[スコア] @Karibash

### ISSUE THREAD

**Issue by Karibash** [CyberAgentHack/web-speed-hackathon-2021-leaderboard#35]
### 注意事項・レギュレーション {{regulation}}

注意事項・レギュレーションを確認して、同意しました

### 計測対象の URL {{url}}

https://cah-web-speed-hackathon-2021.herokuapp.com/

**Comment by Karibash** [comment]
@CyberAgentHack/wsh-admin

VRTの閾値が厳しすぎて、画像/動画周りのチェックが通らないです。。。
下記、VRTの判定結果です。
https://github.com/CyberAgentHack/web-speed-hackathon-2021-leaderboard/suites/4619272372/artifacts/124959898

**Comment by Karibash** [comment]
@CyberAgentHack/wsh-admin

VRTの閾値が厳しすぎて、画像/動画周りのチェックが通らないです。
下記、VRTの判定結果です。
https://github.com/CyberAgentHack/web-speed-hackathon-2021-leaderboard/suites/4619272372/artifacts/124959898

**Comment by 3846masa** [comment]
@Karibash 
Web Speed Hackathon 2021 mini 運営です
参加していただきありがとうございます

差分を確認しましたところ、動画部分で差分が起きているようです

もとの実装には、「ユーザーが OS の視覚効果をオフにしているとき、動画を自動再生しない」実装が含まれています

https://github.com/CyberAgentHack/web-speed-hackathon-2021/blob/135468cc9f69f6f27ba0bc9d3b74d60f1ebe3a40/client/src/components/foundation/PausableMovie/PausableMovie.jsx

おそらくですが、この挙動がデグレしているものと思われますので、今一度実装をご確認いただければ幸いです

**Comment by Karibash** [comment]
@3846masa 

早速のご返信ありがとうございます。

> もとの実装には、「ユーザーが OS の視覚効果をオフにしているとき、動画を自動再生しない」実装が含まれています

こちら実装を修正し、再度VRTを実行した所無事に承認されました。
休日にも関わらず早急な対応いただきありがとうございました。

下記の`CHECKLIST.md`に上記の視覚効果オフの場合の条件を追加された方が良いかなと思いました。
視覚効果オフがデグレしていると他のページも差分判定されるようなので、自分で気づく事が難しいのかなと。。。
https://github.com/CyberAgentHack/web-speed-hackathon-2021/blob/main/docs/CHECKLIST.md#%E6%8A%95%E7%A8%BF%E8%A9%B3%E7%B4%B0---%E5%8B%95%E7%94%BB
